SET SERVEROUTPUT ON;

SELECT * FROM EMPLOYEES where employee_id = 171; -- 8600 + 860 = 9.460
SELECT * FROM jobs;

CREATE OR REPLACE PROCEDURE MYPROC(
id in employees.employee_id%type, 
percent in NUMBER
) IS
BEGIN
   UPDATE EMPLOYEES
    SET SALARY = SALARY * (1 + percent/100)
    WHERE employee_id = id;
END MYPROC;

execute MYPROC(176, 10);

CREATE OR REPLACE PROCEDURE QUERY_EMP(
id in employees.employee_id%type,
name out employees.last_name%type,
salary out employees.salary%type
) IS
BEGIN
    SELECT LAST_NAME, SALARY INTO name, salary FROM EMPLOYEES WHERE EMPLOYEE_ID = id;
END QUERY_EMP;

VARIABLE name VARCHAR2(200);
VARIABLE salary NUMBER;

EXECUTE QUERY_EMP(171, :name, :salary);
PRINT name salary;


CREATE OR REPLACE PROCEDURE CHAMAR_CONSULTA_EMPREGADO(ID IN EMPLOYEES.EMPLOYEE_ID%TYPE)AS
EMP_NOME EMPLOYEES.LAST_NAME%TYPE;
EMP_SALARIO EMPLOYEES.SALARY%TYPE;
BEGIN
    QUERY_EMP(ID, EMP_NOME, EMP_SALARIO);
    DBMS_OUTPUT.PUT_LINE('NOME: ' || EMP_NOME);
    DBMS_OUTPUT.PUT_LINE('SALARIO: ' || EMP_SALARIO);
END CHAMAR_CONSULTA_EMPREGADO;


DECLARE
  ID NUMBER;
BEGIN
  ID := 171;

  CHAMAR_CONSULTA_EMPREGADO(
    ID => ID
  );
END;

create or replace FUNCTION MY_FUNC 
(
  P_NOME VARCHAR2
) RETURN VARCHAR2 IS 
BEGIN
  DBMS_OUTPUT.PUT_LINE('NOME: ' || P_NOME);
  RETURN 'P_NOME';
END MY_FUNC;


DECLARE
    p_nome     VARCHAR2(200);
BEGIN
    p_nome := 'MARCO ANTONIO';
    p_nome := my_func(p_nome => p_nome);
END;


CREATE OR REPLACE FUNCTION CALCULAR_AREA 
(
  P_RADIUS NUMBER 
) RETURN NUMBER AS 

PI NUMBER(7, 3) := 3.147;
V_AREA NUMBER(7, 3);

BEGIN

    V_AREA := PI * (P_RADIUS * P_RADIUS);
    RETURN V_AREA;
  
END CALCULAR_AREA;

CREATE OR REPLACE FUNCTION CALCULAR_AREA 
(
  P_RADIUS NUMBER 
) RETURN NUMBER AS 

PI NUMBER(7, 3) := 3.147;
V_AREA NUMBER(7, 3);

BEGIN

    V_AREA := PI * (P_RADIUS * P_RADIUS);
    RETURN V_AREA;
  
END CALCULAR_AREA;

DECLARE
    p_radius   NUMBER;
BEGIN
    p_radius := 25;
    DBMS_OUTPUT.put_line(calcular_area(p_radius => p_radius));
END;
